import { trpc } from "@/lib/trpc";
import { getPublicDisplayMode, visibleSponsors } from "@/lib/publicCampaign";
import QRCode from "qrcode";
import { ChefHat, Clock3, QrCode, Target, Volume2, Wifi } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

type PublicOrder = { id: number; ticket: number; status: "NEW" | "PREPARING" | "READY" | "DELIVERED" | "CANCELLED"; createdAt: Date };
type Sponsor = { id: number; name: string; imageUrl: string };
type GoalAlert = { id: number; goalAmount: string; salesAtTrigger: string; message: string };
type PixCampaign = { id: number; ticket: number; pixPayload: string; activeUntil: Date };
const time = new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" });
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function PublicCalls() {
  const [, setLocation] = useLocation();
  const snapshot = trpc.operations.snapshot.useQuery(undefined, { refetchInterval: 500 });
  const preview = import.meta.env.DEV ? new URLSearchParams(window.location.search).get("preview") : null;
  const ready = ((snapshot.data?.orders ?? []) as PublicOrder[]).filter(order => order.status === "READY");
  const sponsors = visibleSponsors((snapshot.data?.sponsors ?? []) as (Sponsor & { enabled?: boolean })[]);
  const goalAlert = (preview === "goal" ? { id: -1, goalAmount: "500.00", salesAtTrigger: "500.00", message: "Pesa o cachorro-quente no local de retirada." } : snapshot.data?.goalAlert) as GoalAlert | null | undefined;
  const pixCampaign = (preview === "pix" ? { id: -1, ticket: 99, pixPayload: "00020101021226880014br.gov.bcb.pix2563pix.example.com/pagamento/ifro520400005303986540510.005802BR5913Barraca IFRO6008Vilhena62070503***6304ABCD", activeUntil: new Date(Date.now() + 45_000) } : snapshot.data?.pixCampaign) as PixCampaign | null | undefined;
  const [sponsorIndex, setSponsorIndex] = useState(0);
  const [qrSource, setQrSource] = useState("");
  useEffect(() => { if (sponsors.length < 2) return; const timer = window.setInterval(() => setSponsorIndex(index => (index + 1) % sponsors.length), 5000); return () => window.clearInterval(timer); }, [sponsors.length]);
  useEffect(() => { if (!pixCampaign?.pixPayload) { setQrSource(""); return; } void QRCode.toDataURL(pixCampaign.pixPayload, { width: 420, margin: 1, color: { dark: "#21130f", light: "#fffdf8" } }).then(setQrSource).catch(() => setQrSource("")); }, [pixCampaign?.pixPayload]);
  const current = ready[0];
  const history = ready.slice(1, 5);
  const sponsor = sponsors[sponsorIndex];
  const mode = getPublicDisplayMode(Boolean(goalAlert), Boolean(pixCampaign), Boolean(current));

  return <main className="paper-grid min-h-screen overflow-hidden bg-[#21130f] p-6 text-white lg:p-10"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-[1800px] flex-col"><header className="flex items-center justify-between border-b border-white/15 pb-6"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-orange-400 text-stone-950"><ChefHat className="h-7 w-7" /></div><div><p className="font-display text-2xl font-bold">Barraca Agostina</p><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-300">IFRO • Vilhena</p></div></div><button onClick={() => setLocation("/")} className="hidden rounded-xl border border-white/20 px-4 py-2 text-sm font-bold text-stone-200 hover:bg-white/10 md:block">Voltar à operação</button></header><section className="flex flex-1 flex-col items-center justify-center py-10 text-center">{mode === "goal" ? <GoalAnnouncement goalAlert={goalAlert!} /> : mode === "pix" ? <PixAnnouncement campaign={pixCampaign!} qrSource={qrSource} /> : mode === "ready" ? <><p className="text-sm font-extrabold uppercase tracking-[.26em] text-orange-300">Senha chamada</p><div className="mt-7 grid h-[min(40vw,430px)] w-[min(60vw,630px)] place-items-center rounded-[3.5rem] border border-orange-300/30 bg-[radial-gradient(circle_at_50%_25%,rgba(255,197,101,.32),transparent_32%),linear-gradient(145deg,#9c321e,#5c1b14)] shadow-[0_0_100px_rgba(206,90,39,.3)]"><span className="font-display text-[min(28vw,280px)] font-bold leading-none text-[#fff7e7]">{String(current!.ticket).padStart(2, "0")}</span></div><h1 className="font-display mt-8 text-4xl font-bold md:text-6xl">Seu pedido está pronto!</h1><p className="mt-4 flex items-center gap-2 text-lg text-stone-300"><Volume2 className="h-5 w-5 text-orange-300" />Aguarde a entrega no balcão.</p></> : <><div className="mt-8 grid h-52 w-52 place-items-center rounded-[3rem] border border-dashed border-white/20 bg-white/5"><Clock3 className="h-16 w-16 text-orange-300" /></div><h1 className="font-display mt-8 text-4xl font-bold md:text-6xl">Aguardando o próximo pedido</h1><p className="mt-4 text-lg text-stone-300">As senhas prontas aparecerão aqui.</p></>}</section><footer className="grid gap-5 border-t border-white/15 pt-6 md:grid-cols-[auto_1fr_auto]"><div className="flex items-center gap-2 text-sm font-bold text-emerald-300"><Wifi className="h-4 w-4" />Painel conectado</div><div className="flex flex-wrap justify-center gap-3">{history.map(order => <div key={order.id} className="rounded-2xl border border-white/15 bg-white/5 px-4 py-3"><p className="text-xs font-bold uppercase tracking-[.12em] text-stone-400">Pronto às {time.format(new Date(order.createdAt))}</p><p className="font-display text-2xl font-bold text-orange-200">#{String(order.ticket).padStart(2, "0")}</p></div>)}</div><SponsorSpot sponsor={sponsor} /></footer></div></main>;
}

function GoalAnnouncement({ goalAlert }: { goalAlert: GoalAlert }) { return <div className="max-w-5xl"><div className="mx-auto grid h-24 w-24 place-items-center rounded-3xl bg-orange-400 text-stone-950 shadow-[0_0_80px_rgba(251,146,60,.45)]"><Target className="h-12 w-12" /></div><p className="mt-8 text-sm font-extrabold uppercase tracking-[.28em] text-orange-300">Meta batida</p><h1 className="font-display mt-4 text-5xl font-bold leading-tight text-[#fff7e7] md:text-8xl">{money.format(Number(goalAlert.goalAmount))}</h1><p className="mt-8 text-2xl font-semibold leading-relaxed text-orange-100 md:text-4xl">{goalAlert.message || "Pesa o cachorro-quente no local de retirada."}</p><p className="mt-5 text-sm font-bold uppercase tracking-[.18em] text-stone-400">A comemoração vai começar</p></div>; }
function PixAnnouncement({ campaign, qrSource }: { campaign: PixCampaign; qrSource: string }) { return <div className="grid w-full max-w-5xl items-center gap-10 text-left md:grid-cols-[1fr_auto]"><div><p className="text-sm font-extrabold uppercase tracking-[.26em] text-orange-300">Pagamento PIX</p><h1 className="font-display mt-4 text-5xl font-bold leading-tight text-[#fff7e7] md:text-7xl">Escaneie para pagar</h1><p className="mt-6 text-xl leading-relaxed text-stone-300">Pedido <strong className="text-orange-200">#{String(campaign.ticket).padStart(2, "0")}</strong> confirmado. Aponte a câmera para o QR Code e conclua o pagamento.</p></div><div className="rounded-[2.5rem] bg-[#fffdf8] p-5 shadow-[0_0_80px_rgba(251,146,60,.22)]">{qrSource ? <img src={qrSource} alt="QR Code PIX" className="h-72 w-72 md:h-80 md:w-80" /> : <div className="grid h-72 w-72 place-items-center text-stone-800"><QrCode className="h-16 w-16" /></div>}</div></div>; }
function SponsorSpot({ sponsor }: { sponsor?: Sponsor }) { return <div className="flex min-h-16 min-w-48 items-center justify-center rounded-2xl border border-white/10 bg-white/5 px-4 py-2">{sponsor ? <img src={sponsor.imageUrl} alt={`Patrocinador ${sponsor.name}`} className="max-h-14 max-w-48 object-contain" /> : <span className="text-xs font-bold uppercase tracking-[.15em] text-stone-500">Espaço patrocinadores</span>}</div>; }
