import { trpc } from "@/lib/trpc";
import { visibleSponsors } from "@/lib/publicCampaign";
import { getManualPublicPixPayload, publicPixCampaign, type PixSetting } from "@/lib/pixPayload";
import QRCode from "qrcode";
import { BellRing, ChefHat, Gift, QrCode, Sparkles, Target, Wifi } from "lucide-react";
import { useEffect, useState, type CSSProperties } from "react";
import { useLocation } from "wouter";

type Sponsor = { id: number; name: string; imageUrl: string };
type GoalAlert = { id: number; goalAmount: string; salesAtTrigger: string; message: string };
type PixCampaign = { id: number; ticket: number; pixPayload: string; activeUntil: Date };
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function PublicCalls() {
  const [, setLocation] = useLocation();
  const snapshot = trpc.operations.snapshot.useQuery(undefined, { refetchInterval: 500 });
  const previewParams = import.meta.env.DEV ? new URLSearchParams(window.location.search) : null;
  const preview = previewParams?.get("preview") ?? null;
  const previewSponsors: Sponsor[] = previewParams?.get("sponsors") === "1" ? [
    { id: -101, name: "Apoiador 1", imageUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='160'%3E%3Crect width='100%25' height='100%25' rx='18' fill='%23fff7e7'/%3E%3Ctext x='200' y='92' text-anchor='middle' font-family='Georgia' font-weight='700' font-size='36' fill='%239c321e'%3EAPOIADOR 1%3C/text%3E%3C/svg%3E" },
    { id: -102, name: "Apoiador 2", imageUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='160'%3E%3Crect width='100%25' height='100%25' rx='18' fill='%23fff7e7'/%3E%3Ctext x='200' y='92' text-anchor='middle' font-family='Georgia' font-weight='700' font-size='36' fill='%23b45309'%3EAPOIADOR 2%3C/text%3E%3C/svg%3E" },
    { id: -103, name: "Apoiador 3", imageUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='160'%3E%3Crect width='100%25' height='100%25' rx='18' fill='%23fff7e7'/%3E%3Ctext x='200' y='92' text-anchor='middle' font-family='Georgia' font-weight='700' font-size='36' fill='%231f6f5b'%3EAPOIADOR 3%3C/text%3E%3C/svg%3E" },
  ] : [];
  const sponsors = visibleSponsors((previewSponsors.length ? previewSponsors : snapshot.data?.sponsors ?? []) as (Sponsor & { enabled?: boolean })[]);
  const goalAlert = (preview === "goal" ? { id: -1, goalAmount: "500.00", salesAtTrigger: "500.00", message: "Pesa o cachorro-quente no local de retirada." } : snapshot.data?.goalAlert) as GoalAlert | null | undefined;
  const pixCampaign = (preview === "pix" ? { id: -1, ticket: 99, pixPayload: "00020101021226880014br.gov.bcb.pix2563pix.example.com/pagamento/ifro520400005303986540510.005802BR5913Barraca IFRO6008Vilhena62070503***6304ABCD", activeUntil: new Date(Date.now() + 45_000) } : snapshot.data?.pixCampaign) as PixCampaign | null | undefined;
  const settings = (snapshot.data?.settings ?? []) as PixSetting[];
  const manualPixPayload = getManualPublicPixPayload(settings);
  const manualPixCampaign = manualPixPayload ? { id: -2, ticket: null, pixPayload: manualPixPayload, activeUntil: new Date(Date.now() + 60_000) } : null;
  const activePixCampaign = preview === "pix" ? (previewParams?.get("pixPublic") !== "0" ? pixCampaign : null) : manualPixCampaign ?? publicPixCampaign(pixCampaign, settings);
  const [qrSource, setQrSource] = useState("");
  useEffect(() => { if (!activePixCampaign?.pixPayload) { setQrSource(""); return; } void QRCode.toDataURL(activePixCampaign.pixPayload, { width: 460, margin: 1, color: { dark: "#1c100b", light: "#fffdf7" } }).then(setQrSource).catch(() => setQrSource("")); }, [activePixCampaign?.pixPayload]);
  const mode = goalAlert ? "goal" : activePixCampaign ? "pix" : "promotion";

  return <main className="public-stage min-h-screen overflow-hidden bg-[#1c100b] p-5 text-white lg:p-8"><div className="public-vignette mx-auto flex min-h-[calc(100vh-2.5rem)] max-w-[1920px] flex-col rounded-[2.4rem] border border-white/10 bg-[#27140d]/90 px-6 py-6 shadow-[0_35px_140px_rgba(0,0,0,.5)] lg:px-10 lg:py-8"><header className="flex items-center justify-between gap-6 border-b border-orange-200/15 pb-5"><div className="flex items-center gap-4"><div className="public-logo grid h-14 w-14 place-items-center rounded-2xl bg-orange-400 text-stone-950"><ChefHat className="h-7 w-7" /></div><div><p className="font-display text-2xl font-bold tracking-tight text-[#fff7e7]">Barraca Agostina</p><p className="mt-0.5 text-xs font-black uppercase tracking-[.28em] text-orange-300">IFRO • Vilhena</p></div></div><div className="hidden items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-orange-100 lg:flex"><Sparkles className="h-4 w-4 text-orange-300" />Painel da barraca</div><button onClick={() => setLocation("/")} className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold text-stone-200 transition hover:bg-white/10">Voltar à operação</button></header><section className="relative flex min-h-[min(64vh,680px)] flex-1 flex-col items-center justify-center overflow-hidden py-10 text-center">{mode === "goal" ? <GoalAnnouncement key={goalAlert!.id} goalAlert={goalAlert!} /> : mode === "pix" ? <PixAnnouncement campaign={activePixCampaign!} qrSource={qrSource} /> : <PromotionAnnouncement />}</section><div className="border-t border-orange-200/15 pt-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.12em] text-emerald-300"><Wifi className="h-4 w-4" />Painel conectado</div><SponsorCarousel sponsors={sponsors} /></div></div></main>;
}

function GoalAnnouncement({ goalAlert }: { goalAlert: GoalAlert }) { return <div className="relative z-10 max-w-6xl"><ConfettiBurst /><div className="goal-radiance mx-auto grid h-28 w-28 place-items-center rounded-[2.2rem] bg-orange-400 text-stone-950"><Target className="h-14 w-14" /></div><p className="mt-8 text-sm font-black uppercase tracking-[.36em] text-orange-300">Meta batida</p><h1 className="font-display mt-3 text-6xl font-bold leading-[.9] tracking-tight text-[#fff7e7] drop-shadow-[0_10px_20px_rgba(0,0,0,.4)] md:text-9xl">{money.format(Number(goalAlert.goalAmount))}</h1><div className="mx-auto mt-8 max-w-4xl rounded-3xl border border-orange-200/20 bg-orange-300/10 px-8 py-5 backdrop-blur-sm"><p className="text-2xl font-bold leading-relaxed text-orange-50 md:text-4xl">{goalAlert.message || "Pesa o cachorro-quente no local de retirada."}</p></div><p className="mt-6 text-xs font-black uppercase tracking-[.24em] text-orange-200/70">Comemore com a gente!</p></div>; }
function PromotionAnnouncement() { return <div className="relative z-10 max-w-6xl"><div className="goal-radiance mx-auto grid h-28 w-28 place-items-center rounded-[2.2rem] bg-orange-400 text-stone-950"><BellRing className="h-14 w-14" /></div><p className="mt-8 text-sm font-black uppercase tracking-[.36em] text-orange-300">Desafio da barraca</p><h1 className="font-display mt-4 text-5xl font-bold leading-[.95] text-[#fff7e7] md:text-8xl">Prepare-se para<br />o som da sirene!</h1><div className="mx-auto mt-8 max-w-5xl rounded-3xl border border-orange-200/20 bg-orange-300/10 px-8 py-6 backdrop-blur-sm"><div className="flex flex-col items-center gap-4 md:flex-row md:text-left"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-orange-400 text-stone-950"><Gift className="h-7 w-7" /></div><p className="text-2xl font-bold leading-relaxed text-orange-50 md:text-4xl">O primeiro a chegar ao local de retirada do cachorro-quente quando a sirene tocar ganha um gratuitamente!</p></div></div><p className="mt-6 text-xs font-black uppercase tracking-[.24em] text-orange-200/70">Fique atento ao sinal</p></div>; }
function PixAnnouncement({ campaign, qrSource }: { campaign: Omit<PixCampaign, "ticket"> & { ticket: number | null }; qrSource: string }) { return <div className="relative z-10 grid w-full max-w-6xl items-center gap-12 text-left lg:grid-cols-[1fr_auto]"><div><p className="text-sm font-black uppercase tracking-[.3em] text-orange-300">Pagamento PIX</p><h1 className="font-display mt-4 text-6xl font-bold leading-[.95] text-[#fff7e7] md:text-8xl">Escaneie<br />para pagar</h1><div className="mt-7 max-w-xl border-l-2 border-orange-300 pl-5 text-xl leading-relaxed text-orange-50">{campaign.ticket ? <>Pedido <strong className="text-orange-200">#{String(campaign.ticket).padStart(2, "0")}</strong> confirmado. </> : <>QR Code ativado pelo caixa. </>}Aponte a câmera para o QR Code e conclua o pagamento.</div></div><div className="rounded-[3rem] border border-orange-200/30 bg-[#fffdf7] p-6 shadow-[0_0_100px_rgba(251,146,60,.25)]">{qrSource ? <img src={qrSource} alt="QR Code PIX" className="h-80 w-80 lg:h-[25rem] lg:w-[25rem]" /> : <div className="grid h-80 w-80 place-items-center text-stone-800"><QrCode className="h-16 w-16" /></div>}</div></div>; }
function SponsorCarousel({ sponsors }: { sponsors: Sponsor[] }) { const items = sponsors.length > 1 ? [...sponsors, ...sponsors] : sponsors; return <div className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-[#150a07]/50 py-3"><div className="mb-2 px-5 text-[10px] font-black uppercase tracking-[.26em] text-orange-200/70">Patrocinadores</div>{items.length ? <div className={sponsors.length > 1 ? "sponsor-track" : "flex justify-center px-5"}>{items.map((sponsor, index) => <div key={`${sponsor.id}-${index}`} className="sponsor-card"><img src={sponsor.imageUrl} alt={`Patrocinador ${sponsor.name}`} className="h-20 w-52 object-contain lg:h-28 lg:w-72" /></div>)}</div> : <div className="px-5 pb-2 text-center text-xs font-bold uppercase tracking-[.15em] text-stone-500">Espaço reservado aos apoiadores da festa</div>}</div>; }
function ConfettiBurst() { const colors = ["#ffb11b", "#fb7185", "#34d399", "#60a5fa", "#f8fafc", "#fb923c"]; return <div className="confetti-burst" aria-hidden="true">{Array.from({ length: 52 }, (_, index) => { const drift = ((index * 47) % 230) - 115; const style = { left: `${(index * 37) % 100}%`, top: `${8 + ((index * 29) % 24)}%`, backgroundColor: colors[index % colors.length], "--drift": `${drift}px`, "--delay": `${(index % 11) * 45}ms`, "--turn": `${(index % 2 ? 1 : -1) * (120 + (index % 5) * 35)}deg` } as CSSProperties; return <span key={index} className={index % 3 === 0 ? "confetti-piece confetti-ribbon" : "confetti-piece"} style={style} />; })}</div>; }
