import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Pencil, Power } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type Sponsor = { id: number; name: string; imageUrl: string; enabled: boolean; sortOrder: number };

export default function SponsorControls({ sponsors, refresh }: { sponsors: Sponsor[]; refresh: () => void }) {
  const [editing, setEditing] = useState<Sponsor | null>(null);
  const save = trpc.operations.saveSponsor.useMutation({ onSuccess: () => { toast.success("Patrocinador atualizado."); setEditing(null); refresh(); }, onError: error => toast.error(error.message) });
  if (!sponsors.length) return null;
  return <section className="mt-6 rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-stone-500">Gestão de mídia</p><h2 className="font-display text-2xl font-bold">Patrocinadores cadastrados</h2><p className="mt-1 text-sm text-stone-600">Edite a identificação ou retire uma marca do rodízio sem apagar seu cadastro.</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{sponsors.map(item => <article key={item.id} className="overflow-hidden rounded-2xl border border-stone-200 bg-stone-50"><div className="flex gap-4 p-4"><img src={item.imageUrl} alt={item.name} className="h-20 w-28 rounded-xl bg-white object-contain p-2" /><div className="min-w-0 flex-1"><p className="truncate font-bold text-stone-900">{item.name}</p><p className="mt-1 text-xs font-semibold text-stone-500">Ordem {item.sortOrder} · {item.enabled ? "No rodízio" : "Pausado"}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(item)}><Pencil className="mr-1 h-3.5 w-3.5" />Editar</Button><Button size="sm" variant="outline" disabled={save.isPending} onClick={() => save.mutate({ id: item.id, name: item.name, imageUrl: item.imageUrl, enabled: !item.enabled, sortOrder: item.sortOrder })}><Power className="mr-1 h-3.5 w-3.5" />{item.enabled ? "Pausar" : "Ativar"}</Button></div></div></div></article>)}</div>{editing ? <div className="mt-5 rounded-2xl border border-orange-200 bg-orange-50/60 p-4"><p className="font-bold text-stone-900">Editar patrocinador</p><div className="mt-3 grid gap-3 md:grid-cols-2"><Input value={editing.name} onChange={event => setEditing(current => current ? { ...current, name: event.target.value } : current)} placeholder="Nome" /><Input value={editing.imageUrl} onChange={event => setEditing(current => current ? { ...current, imageUrl: event.target.value } : current)} placeholder="URL da imagem" /><Input type="number" min="0" value={editing.sortOrder} onChange={event => setEditing(current => current ? { ...current, sortOrder: Number(event.target.value) || 0 } : current)} placeholder="Ordem" /><div className="flex items-center justify-between rounded-xl border border-orange-200 bg-white px-3"><span className="text-sm font-bold">Exibir no rodízio</span><Switch checked={editing.enabled} onCheckedChange={enabled => setEditing(current => current ? { ...current, enabled } : current)} /></div></div><div className="mt-4 flex gap-3"><Button disabled={!editing.name || !editing.imageUrl || save.isPending} onClick={() => save.mutate(editing)} className="rounded-xl bg-[#9c321e] hover:bg-[#7f2819]">Salvar edição</Button><Button variant="outline" onClick={() => setEditing(null)} className="rounded-xl">Cancelar</Button></div></div> : null}</section>;
}
